version: 2

models:
  - name: customer
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_customer
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null

      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
